auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Chenkov's Blog”
title: CHENKOV
description: Everything about CHENKOV.
url: http://CHENKOV21.github.io
feed: /atom.xml
author_info: <a href="http://chenkov21.github.io/">chenkov</a>
